name: sd-42-mpt-passes-4-0-final-1B-26B-baseline
image: mosaicml/llm-foundry:2.1.0_cu121-e772a47
scheduling:
  resumable: true
  priority: medium
  preemptible: true
compute:
  gpus: 8
  cluster: r1z1
parameters:
  max_seq_len: 2048
  run_name: mpt-passes-4.0-final-1B-26B-baseline
  ckpt_fmt_run_name: mpt-passes-4.0-final-1B-26B-baseline
  dataset: mpt
  seed: 42
  lr: 0.0002
  bs: 512
  models:
  - model_name: ${run_name}
    load_path: oci://mosaicml-internal-checkpoints/zack/me-fomo-data-filtering/${dataset}/gpt4-tiktoken-seqlen-${max_seq_len}/final/${ckpt_fmt_run_name}-bs-${bs}-lr-${lr}-sd-${seed}/ckpts/latest-rank0.pt.symlink
    model:
      name: mpt_causal_lm
      init_device: meta
      d_model: 2048
      n_heads: 16
      n_layers: 24
      expansion_ratio: 4
      max_seq_len: ${max_seq_len}
      vocab_size: 100352
      tokenizer_name: ${tokenizer_name}
      no_bias: true
      norm_type: low_precision_layernorm
      emb_pdrop: 0
      resid_pdrop: 0
      init_config:
        init_nonlinearity: relu
        name: kaiming_normal_
      attn_config:
        alibi: true
        attn_impl: triton
        clip_qkv: 6
        attn_uses_sequence_id: false
        attn_pdrop: 0
    tokenizer:
      name: ${tokenizer_name}
      kwargs:
        model_name: gpt-4
  precision: amp_bf16
  tokenizer_name: tiktoken
  device_eval_batch_size: 16
  fsdp_config:
    activation_checkpointing: false
    activation_checkpointing_reentrant: false
    activation_cpu_offload: false
    limit_all_gathers: true
    mixed_precision: PURE
    sharding_strategy: FULL_SHARD
    state_dict_type: full
    verbose: false
  loggers:
    wandb:
      project: me-fomo-data-filtering
      tags:
      - eval
      - dataset-${dataset}
      name: eval-${run_name}-sd-${seed}
      group: eval-${run_name}
  icl_tasks: eval/yamls/tasks_v2.yaml
  eval_gauntlet: eval/yamls/eval_gauntlet_v2.yaml
  icl_seq_len: 2048
integrations:
- integration_type: git_repo
  git_branch: zack/me-fomo-data-pruning
  git_repo: zankner/llm-foundry
  pip_install: .[gpu]
  ssh_clone: true
- integration_type: wandb
  entity: mosaic-ml
  project: me-fomo-data-filtering
- integration_type: pip_packages
  packages:
  - tiktoken
command: |
  pip install --upgrade "mosaicml==0.20.1"
  cd llm-foundry/scripts
  composer eval/eval.py /mnt/config/parameters.yaml || (echo "Command failed - killing python" && pkill python && exit 1)