name: # set by launch script

env_variables:
  - key: NCCL_IB_PCI_RELAXED_ORDERING
    value: 1
  - key: NCCL_COLLNET_ENABLE
    value: "0"

integrations:
  - integration_type: git_repo
    git_branch: zack/data-filtering
    git_repo: zankner/llm-foundry
    pip_install: .[gpu]
    ssh_clone: true
  - integration_type: wandb
    entity: mosaic-ml
    project: me-fomo-data-filtering
  - integration_type: "pip_packages"
    packages:
      - tiktoken

# image: mosaicml/pytorch:2.1.0_cu121-nightly20230827-python3.10-ubuntu20.04
image: mosaicml/llm-foundry:2.1.0_cu121-e772a47
cluster: # Set in launch script
gpu_num: # Set in launch script

command: |-
  source /secrets/secrets.env
  export AWS_PROFILE=data-force-one
  pip install -U wandb==0.15.4
  cd llm-foundry/scripts
  composer train/train.py /mnt/config/parameters.yaml || (echo "Command failed - killing python" && pkill python && exit 1)

parameters:
  global_seed: # Set in launch script
  max_seq_len: 4096 # max tokens per sequence during training

  run_name: #Set in launch script

  # Model
  model:
    name: mpt_causal_lm
    init_device: meta
    d_model: # Set in launch script
    n_heads: # Set in launch script
    n_layers: # Set in launch script
    expansion_ratio: 4
    max_seq_len: ${max_seq_len}
    vocab_size: 100352 # update for hero run with custom tokenizer
    tokenizer_name: ${tokenizer_name}
    no_bias: true
    norm_type: low_precision_layernorm
    emb_pdrop: 0
    resid_pdrop: 0
    init_config:
      init_nonlinearity: relu
      name: kaiming_normal_
    attn_config:
      alibi: true
      attn_impl: triton
      clip_qkv: 6
      attn_uses_sequence_id: false
      attn_pdrop: 0

  # Tokenizer
  tokenizer_name: tiktoken
  tokenizer:
    name: ${tokenizer_name} # default tokenizer used for MPT
    kwargs:
      model_name: gpt-4

  # Optimization
  global_train_batch_size: # Set by launch script
  max_duration: # Set by launch script

  optimizer:
    name: decoupled_lionw
    lr: # Set by launch script
    betas:
      - 0.9
      - 0.95
    weight_decay: # Set by launch script

  scheduler:
    name: cosine_with_warmup
    t_warmup: 0.06dur
    alpha_f: 0.1

  # System
  seed: ${global_seed}
  precision: amp_bf16
  device_train_microbatch_size: # Set in launch script
  device_eval_batch_size: # Set in launch script

  # FSDP
  fsdp_config:
    activation_checkpointing: false
    activation_checkpointing_reentrant: false
    activation_cpu_offload: false
    limit_all_gathers: true
    mixed_precision: PURE
    sharding_strategy: FULL_SHARD
    state_dict_type: full
    verbose: false

  # Logging
  eval_first: false
  eval_interval: 0.1dur
  log_to_console: true
  console_log_interval: 100ba
  progress_bar: false
  python_log_level: DEBUG
  loggers:
    wandb:
      project: me-fomo-data-filtering
      tags:
        - seed-${global_seed}
      group: ${run_name}

  # Checkpointing
  autoresume: # Set by launch script
  save_filename: ba{batch}/rank{rank}.pt
  save_folder: # Set by launch script
  save_interval: 500ba # update for hero run, e.g. 2000ba
  save_num_checkpoints_to_keep: 1

  # Algos and Callbacks
  algorithms:
    gradient_clipping:
      clipping_threshold: 1
      clipping_type: norm

  callbacks:
    lr_monitor: {}
    memory_monitor: {}
    runtime_estimator: {}
    scheduled_gc:
      batch_interval: 2000
    speed_monitor:
      window_size: 1
    gpu_hour_logger: {}

  # Dataloaders
  eos_token_id: 0 # update for hero run with custom tokenizer
  num_canonical_nodes: 128 # update for hero run, must be codivisible by # physical nodes

  # In-context-learning tasks
  icl_tasks: eval/yamls/tasks.yaml
  eval_gauntlet: eval/yamls/eval_gauntlet.yaml
  icl_seq_len: 2048

  # Train loader
  train_loader:
    name: text
    drop_last: true
    num_workers: 1
    dataset:
      cache_limit: 2tb
      download_timeout: 360
      eos_token_id: ${eos_token_id}
      max_seq_len: ${max_seq_len}
      num_canonical_nodes: ${num_canonical_nodes}
      shuffle: true
      sampling_method: fixed
      shuffle_algo: py1br
      predownload: 4194304
      shuffle_block_size: 4194304
      shuffle_seed: ${global_seed}
      local: /tmp/dataset/train
      remote: # Set by launch script
      split: null
